### ISSUE TITLE
Forced caching in BattleriteClientFactory

### ISSUE THREAD

**Issue by brianebeling** [RethoughtSolutions/Battlerite.NET#1]
The BattleriteClientFactory currently also knows about other factories.
That itself is not the cause, but there is no way of customizing the behaviour in the single factory method.

- A solution would be to add more methods for more customization or more factories
- Or some sort of builder pattern where the user can switch out clients and the non-specificied ones default to the non-caching barebones version

**Comment by RethoughtSolutions** [comment]
Fixed with a fluent builder pattern
